[package]
name = "amscrapper-rs"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib"]

[[bin]]
name = "amscrapperrs"
path = "src/main.rs"

[dependencies]
uiautomation = "0.17.1"
regex = "1.11.1"
winvd = "0.0.48"
serde_json = "1.0.140"
serde = { version = "1.0.140", features = ["derive"] }
anyhow = "1.0.97"
once_cell = "1.21.1"

[dependencies.windows]
version = "0.58"
features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"]
