[package]
name = "amscrapper-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
uiautomation = "0.17.1"
winprocinfo = "0.1.1"
regex = "1.11.1"
winvd = "0.0.48"

[dependencies.windows]
version = "0.58" # Current version as of writing
features = [
    "implement",
    "Win32_System_Com",
    "Win32_UI_Shell_Common",        # for IObjectArray
    "Win32_UI_WindowsAndMessaging", # for TranslateMessage etc.
    "Win32_Foundation",             # for FindWindowW
    "Win32_System_Threading",       # For CreateThread
]
